name: expense_tracker
description: A simple expense tracker for web
publish_to: 'none'
version: 1.0.0
environment:
  sdk: '>=2.18.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  uuid: ^3.0.6

development_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
